### ISSUE TITLE
Suggestion: integrating this repo into patternite.com

### ISSUE THREAD

**Issue by duncster94** [DovAmir/awesome-design-patterns#31]
Hey there, really awesome repo! I think this is a fantastic resource.

Myself and a few of my colleagues recently created a [website](https://patternite.com/) for crowd-sourced design patterns - I was wondering if any of the authors here would be interested in contributing their patterns from this repo to the site? Just a little suggestion 😄

**Comment by DovAmir** [comment]
declined
